GET http://localhost:4000/api/homeworks
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTVhNTAwMWE1ODRmMzYyNGQ5NWUyZCIsImlhdCI6MTYyMTQ4MDEyMCwiZXhwIjoxNjIxNTY2NTIwfQ.CuDp8UP1MejCTbTHSfb-lP2KcftvuCCxbSeKAeTRtZI

###

POST http://localhost:4000/api/homeworks
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTVhNTAwMWE1ODRmMzYyNGQ5NWUyZCIsImlhdCI6MTYyMTQ4MDEyMCwiZXhwIjoxNjIxNTY2NTIwfQ.CuDp8UP1MejCTbTHSfb-lP2KcftvuCCxbSeKAeTRtZI

{
    "name": "Cantar"
}


###

DELETE http://localhost:4000/api/homeworks/60a5d70f65c8e559349acd1d
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTVhNTAwMWE1ODRmMzYyNGQ5NWUyZCIsImlhdCI6MTYyMTQ4MDEyMCwiZXhwIjoxNjIxNTY2NTIwfQ.CuDp8UP1MejCTbTHSfb-lP2KcftvuCCxbSeKAeTRtZI
